chore: update codemagic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -11,6 +11,11 @@ workflows:
       android_signing:
         - KR_TV_DEV
     scripts:
+      - name: Load Firebase configuration
+        script: |
+          #!/usr/bin/env sh
+          set -e # exit on first failed command
+          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/menuboss-kr/android/app/google-services.json
       - name: Make Gradle Wrapper Executable
         script: |
           chmod +x ./gradlew
@@ -25,7 +30,7 @@ workflows:
       - app/build/outputs/**/*.apk
     publishing:
       firebase:
-        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+        firebase_service_account: $KR_ANDROID_TV_DEV_FIREBASE_SERVICE_ACCOUNT
         android:
           app_id: 1:1087980522226:android:3e8715ca1c475ebab21e6b
           groups:
