chore: update codemagic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -11,11 +11,11 @@ workflows:
       android_signing:
         - KR_TV_DEV
     scripts:
-      - name: Load Firebase configuration
-        script: |
-          #!/usr/bin/env sh
-          set -e # exit on first failed command
-          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/menuboss-kr/android/app/google-services.json
+#      - name: Load Firebase configuration
+#        script: |
+#          #!/usr/bin/env sh
+#          set -e # exit on first failed command
+#          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/dev/google-services.json
       - name: Make Gradle Wrapper Executable
         script: |
           chmod +x ./gradlew
